name: 🐞 Bug Report 
description: Report a bug in jArchi
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: input
    id: jArchi-version
    attributes:
      label: jArchi Version
      description: Which version of jArchi are you using?
      placeholder: ex. 1.6.0
    validations:
      required: true
  - type: input
    id: archi-version
    attributes:
      label: Archi Version
      description: Which version of Archi are you using?
      placeholder: ex. 5.4.0
    validations:
      required: true
  - type: input
    id: os-kind
    attributes:
      label: Operating System
      description: Which operating system and version are you using?
      placeholder: ex. Windows 11, macOS Sonoma 14.5, Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.
        Please attach an example jArchi script and/or an *.archimate file that demonstrates the problem, if possible.
      placeholder: |
        Please enter a description of the issue. Here you can also attach script files, model files, screenshots, or other files.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: false
